name: cmake_build_and_test_onpush

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: make test
      run: make test
  
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: make test
      run: make test
